# Generated by Django 2.2.2 on 2019-06-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=255)),
                ('resource_number', models.IntegerField(max_length=10)),
                ('resource_website', models.CharField(max_length=60)),
                ('month', models.CharField(choices=[('FA', 'Financial Assistance'), ('FO', 'Food'), ('HO', 'Housing'), ('MD', 'Medical & Dental'), ('MH', 'Mental Health')], default='Pick a Category', max_length=21)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='bee_resourceful_app.User')),
            ],
        ),
    ]
