# Generated by Django 2.2.2 on 2019-06-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bee_resourceful_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='month',
            new_name='category',
        ),
    ]
