# Generated by Django 2.2.2 on 2019-06-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee_resourceful_app', '0003_auto_20190603_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
